CREATE TABLE USERS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  FIRST_NAME TEXT NOT NULL,
  LAST_NAME TEXT NOT NULL,
  EMAIL TEXT NOT NULL,
  ENCRYPTED_PASSWORD TEXT NOT NULL,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL
);

CREATE TABLE BOARDS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  NAME TEXT NOT NULL,
  SLUG TEXT,
  USER_ID INTEGER NOT NULL,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX BOARDS_USER_ID_INDEX
  ON BOARDS
  (USER_ID);

CREATE TABLE LISTS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  NAME TEXT,
  POSITION INTEGER DEFAULT 0,
  BOARD_ID INTEGER,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (BOARD_ID) REFERENCES BOARDS (ID) ON DELETE CASCADE
);

CREATE INDEX LISTS_BOARD_ID_INDEX
  ON LISTS
  (BOARD_ID);

CREATE TABLE CARDS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  NAME TEXT,
  DESCRIPTION TEXT,
  POSITION INTEGER DEFAULT 0,
  TAGS TEXT,
  LIST_ID INTEGER NOT NULL,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (LIST_ID) REFERENCES LISTS (ID) ON DELETE CASCADE
);

CREATE INDEX CARDS_LIST_ID_INDEX
  ON CARDS
  (LIST_ID);

CREATE TABLE USER_BOARDS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  USER_ID INTEGER NOT NULL,
  BOARD_ID INTEGER NOT NULL,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (BOARD_ID) REFERENCES BOARDS (ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX USER_BOARDS_BOARD_ID_INDEX
  ON USER_BOARDS
  (BOARD_ID);

CREATE UNIQUE INDEX USER_BOARDS_USER_ID_BOARD_ID_INDEX
  ON USER_BOARDS
  (USER_ID, BOARD_ID);

CREATE INDEX USER_BOARDS_USER_ID_INDEX
  ON USER_BOARDS
  (USER_ID);

  
CREATE TABLE CARD_MEMBERS
(
  ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  CARD_ID INTEGER NOT NULL,
  USER_BOARD_ID INTEGER NOT NULL,
  INSERTED_AT TEXT NOT NULL,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (CARD_ID) REFERENCES CARDS (ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_BOARD_ID) REFERENCES USER_BOARDS (ID) ON DELETE CASCADE
);

CREATE INDEX CARD_MEMBERS_CARD_ID_INDEX
  ON CARD_MEMBERS
  (CARD_ID);

CREATE UNIQUE INDEX CARD_MEMBERS_CARD_ID_USER_BOARD_ID_INDEX
  ON CARD_MEMBERS
  (CARD_ID, USER_BOARD_ID);

CREATE INDEX CARD_MEMBERS_USER_BOARD_ID_INDEX
  ON CARD_MEMBERS
  (USER_BOARD_ID);

CREATE TABLE COMMENTS
(
  ID INTEGER NOT NULL PRIMARY KEY,
  TEXT TEXT,
  USER_ID INTEGER,
  CARD_ID INTEGER,
  INSERTED_AT TEXT,
  UPDATED_AT TEXT NOT NULL,
  FOREIGN KEY (CARD_ID) REFERENCES CARDS (ID) ON DELETE CASCADE,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE INDEX COMMENTS_CARD_ID_INDEX
  ON COMMENTS
  (CARD_ID);

CREATE INDEX COMMENTS_USER_ID_INDEX
  ON COMMENTS
  (USER_ID);


